services:

  nginx:
    image: nginx
    volumes:
      - challengeloc:/var/www/certbot
      - certloc:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot


  certbot:
    image: certbot/certbot
    volumes:
      - challengeloc:/var/www/certbot
      - certloc:/etc/letsencrypt
    entrypoint: |
      certbot certonly --webroot -w /var/www/certbot \
      -d xn--hy1bt9b37a.com \
      --email hanharry2@gmail.com \
      --agree-tos \
      --no-eff-email


  web:
    build: ./web
    expose:
      - "8080"



volumes:
  certloc:
  challengeloc: