services:

  nginx:
    image: nginx
    volumes:
      - challengeloc:/var/www/certbot:ro
      - certloc:/etc/letsencrypt:ro
      - ./nginx/conf.d/default.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"


  certbot:
    image: certbot/certbot
    volumes:
      - challengeloc:/var/www/certbot:rw
      - certloc:/etc/letsencrypt:rw
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do certbot renew --quiet; sleep 12h & wait $!; done;"



  web:
    build: ./web
    expose:
      - "8080"



volumes:
  certloc:
  challengeloc: