services:

  nginx:
    image: nginx
    volumes:
      - certloc:/etc/letsencrypt:ro
      - challengeloc:/var/www/letsencrypt
      - ./nginx/conf.d/default.conf:/etc/nginx/nginx.conf
      - ./web:/web
    ports:
      - "80:80"
      - "443:443"


  certbot:
    image: certbot/certbot
    volumes:
      - certloc:/etc/letsencrypt:rw
      - challengeloc:/var/www/letsencrypt
      - ./certbot/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]



  web:
    build: ./web
    expose:
      - "8080"



volumes:
  certloc:
  challengeloc:
