services:

  nginx:
    image: nginx
    volumes:
      - challengeloc:/var/www/certbot:ro
      - certloc:/etc/letsencrypt:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
      - "443:443"


  certbot:
    image: certbot/certbot
    volumes:
      - challengeloc:/var/www/certbot:rw
      - certloc:/etc/letsencrypt:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email hanharry2@gmail.com --agree-tos --no-eff-email -d xn--hw4bo2pv3cz9f.com


  web:
    build: ./web
    expose:
      - "8080"



volumes:
  certloc:
  challengeloc: